services:
  - type: web
    name: emp-service
    env: docker
    plan: free
    branch: main
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: emp-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: emp-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: emp-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: emp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: emp-db
          property: password

databases:
  - name: emp-db
    plan: free
    databaseName: chatapp
    user: chatapp_user
