services:
  - type: web
    name: emp-service
    env: docker
    plan: free
    branch: main
    envVars:
      - key: DB_URL
        fromDatabase:
          name: emp-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: emp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: emp-db
          property: password

databases:
  - name: emp-db
    plan: free
    databaseName: chatapp
    user: chatapp_user
